import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import { parseUserCookie } from "@/lib/auth";
import "./globals.css";
import { AppApolloProvider } from "@/components/providers/AppApolloProvider";
import { CategoryMetadataProvider } from "@/state/CategoryMetadataContext";
import { MainNav } from "@/components/nav/MainNav";
import { AuthProvider } from "@/state/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await parseUserCookie();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider initialUser={user}>
          <header className="sticky top-0 z-50 bg-surface border-b border-default">
            <div className="mx-auto w-full max-w-6xl px-6 py-3 flex items-center gap-4">
              <Link href="/" className="font-semibold">Finanz</Link>
              <MainNav />
            </div>
          </header>
          <AppApolloProvider>
            <CategoryMetadataProvider>
              <main className="min-h-[calc(100vh+1px)]">
                {children}
              </main>
            </CategoryMetadataProvider>
          </AppApolloProvider>
          <footer className="bg-surface border-t border-default">
            <div className="mx-auto w-full max-w-6xl px-6 py-6 flex flex-col sm:flex-row items-start sm:items-center gap-2 sm:gap-6 justify-between text-sm text-muted">
              <div className="flex items-center gap-2">
                <span className="font-semibold text-foreground">Finanz</span>
                <span>© {new Date().getFullYear()}</span>
              </div>
              <nav className="flex items-center gap-4">
                <Link href="/dashboard" className="hover:text-[color:var(--accent)]">Dashboard</Link>
                <Link href="/expenses" className="hover:text-[color:var(--accent)]">Expenses</Link>
                <a href="#" className="hover:text-[color:var(--accent2)]">Privacy</a>
              </nav>
            </div>
          </footer>
        </AuthProvider>
      </body>
    </html>
  );
}
