import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import { parseUserCookie } from "@/lib/auth";
import "./globals.css";
import { AppApolloProvider } from "@/components/providers/AppApolloProvider";
import { CategoryMetadataProvider } from "@/state/CategoryMetadataContext";
import { MainNav } from "@/components/nav/MainNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = parseUserCookie();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="bg-surface border-b border-default">
          <div className="mx-auto w-full max-w-6xl px-6 py-3 flex items-center gap-4">
            <Link href="/" className="font-semibold">Finanz</Link>
            <MainNav user={user} />
          </div>
        </header>
        <AppApolloProvider>
          <CategoryMetadataProvider>
            {children}
          </CategoryMetadataProvider>
        </AppApolloProvider>
      </body>
    </html>
  );
}
